[package]
name = "astrocommunity-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"], default-features = false }
serde = { version = "1", features = ["derive"], default-features = false }
serde_json = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
], default-features = false }
clap = { version = "4", features = ["derive", "std"], default-features = false }
anyhow = "1.0.71"
